<div class="container z-depth-5">
	<h2 class="center-align">Agregar transaccion</h2>
	<div class="row">
		<div class="container">
			<form action="<?php echo APP_URL."transacciones/agregar"; ?>" method="POST">
				<div class="row">
					<label for="description">Descripcion</label>
					<textarea name="description"></textarea>

					<label for="date">Fecha</label>
					<input class="datepicker" type="date" name="date" value="<?php echo date("Y-m-d"); ?> ">

					<label for="amount">Monto</label>
					<input type="number" name="amount" >
					
					<div class="input-field col">
					    <select name="category_id">
                            <option disabled selected>Elige una categoria</option>
                                <?php foreach ($this->categorias as $categoria) { ?>
                            <option value="<?php echo $categoria["id"]; ?>">
                                <?php echo $categoria["name"]; ?></option>
                                <?php } ?>
                        </select>
					</div>
					<div class="input-field col">
					    <select name="account_id">
                            <option disabled selected>Elige una cuenta</option>
                                <?php foreach ($this->cuentas as $cuenta) { ?>
                            <option value="<?php echo $cuenta["id"]; ?>">
                                <?php echo $cuenta["name"]; ?></option>
                                <?php } ?>
                        </select>
					</div>
				</div>
				<div class="row center-align">
					<button class="waves-effect waves-light btn" type="submit">Guardar</button>
				</div>
			</form>
		</div>
	</div>
</div>
