<div class="container z-depth-5">
	<h2 class="center-align">Agregar categoria</h2>
	<div class="row">
		<div class="container">
			<form action="<?php echo APP_URL."categorias/agregar"; ?>" method="POST">
				<div class="row">
					<label for="name">Nombre</label>
					<input type="text" name="name">
					
				</div>
				<div class="row center-align">
					<button class="waves-effect waves-light btn" type="submit">Guardar</button>
				</div>
			</form>
		</div>
	</div>
</div>
