<div class="row z-depth-5">
	<h2 class="center-align">Lista de Categorias</h2>
	<div class="row">
          
		<div class="container right-align">
			<a class="waves-effect waves-light btn" href="<?php echo APP_URL."categorias/agregar"; ?>"><i class="material-icons left">add</i>Categoria</a>
		</div>
		<div class="row">
			<table class="highlight">
				<thead>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
				    <?php foreach ($this->categorias as $categoria): ?>
                        <tr>
                           <td><?php  echo $categoria['id'];?></td>
					       <td><?php  echo $categoria['name'];?></td>
                            <td>
                            	<a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>"><i class="material-icons">edit</i></a>
                            	<a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
