<div class="row z-depth-5">
	<h2 class="center-align">Transacciones de cuenta</h2>
	<div class="row">
		<div class="container right-align">
			<a class="waves-effect waves-light btn" href="<?php echo APP_URL."pages/agregar"; ?>"><i class="material-icons left">add</i>Transaccion</a>
		</div>
		<div class="row">
			<table class="highlight">
				<thead>
					<tr>
						<th>Id</th>
						<th>Descripcion</th>
						<th>Fecha</th>
						<th>Monto</th>
						<th>Categoria</th>
						<th>Cuenta</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
				
					<?php foreach ($this->pagess as $pag): ?>
                        <tr>
                            <td><?php echo $pag["transactions"]["id"]; ?></td>
                            
                            <td><?php echo $pag["transactions"]["description"]; ?></td>
                            
                            <td><?php $date=date_create($pag["transactions"]["date"]);
                                echo date_format($date,'d/m/Y');  ?></td>
                                
                            <td><?php echo $pag["transactions"]["amount"]; ?></td>
                            
                            <td><?php echo $pag["categories"]["name"]; ?></td>
            
                            <td><?php echo $pag["accounts"]["name"]; ?>
                            </td>
                            <td>
                            	<a href="<?php echo APP_URL."pages/editar/".$pag["transactions"]["id"]; ?>"><i class="material-icons">edit</i></a>
                            	<a href="<?php echo APP_URL."pages/eliminar/".$pag["transactions"]["id"]; ?>"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <?php
                    $suma=0;
                    foreach ($this->pagess as $pag):
                    $suma+=$pag["transactions"]["amount"];?>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Balance</th>
                        <th><?php  echo $suma; ?></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    <?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
