<div class="row z-depth-5">
	<h2 class="center-align">Lista de Cuentas</h2>
	<div class="row">
          
		<div class="container right-align">
			<a class="waves-effect waves-light btn" href="<?php echo APP_URL."cuentas/agregar"; ?>"><i class="material-icons left">add</i>Cuenta</a>
		</div>
		<div class="row">
			<table class="highlight">
				<thead>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Accion</th>
					</tr>
				</thead>
				<tbody>
				    <?php foreach ($this->cuentas as $cuenta): ?>
                        <tr>
                           <td><?php  echo $cuenta['id'];?></td>
					       <td><?php  echo $cuenta['name'];?></td>
                            <td>
                            	<a href="<?php echo APP_URL."cuentas/editar/".$cuenta["id"]; ?>"><i class="material-icons">edit</i></a>
                            	<a href="<?php echo APP_URL."cuentas/eliminar/".$cuenta["id"]; ?>"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
